### ISSUE TITLE
Dispatch event once editor is initialized

### ISSUE THREAD

**Issue by 0xMurage** [Lumieducation/H5P-Nodejs-library#1163]
Can we dispatch an event on the web component once the editor is initialized ?
Or is it possible to override the editor loading message to a custom one/custom styled loader?

**Comment by sr258** [comment]
There already is such an event: https://docs.lumi.education/npm-packages/h5p-webcomponents#editorloaded

Or do you mean an event after the editor was first initialized (Hub UI with library selector is displayed)?

**Comment by 0xMurage** [comment]
Yes. Since the `editorloaded` event is dispatched once a user selects the content type they are going to create (after selecting the `use` button where content type is already installed)

**Comment by sr258** [comment]
I understand what you need. We don't emit such an event at the moment. 

I'll have to dig into the H5P editor core code to check if H5P fires such an event and if it is possible to map the global event to the individual components (the editorloaded event, for instance, is actually global and the web component has logic to only relay it to the component it comes from). I guess I won't have time to do this until tomorrow or the day after.

**Comment by sr258** [comment]
I've had time to look into this.

You can customize the loading text in this file: `h5p/editor/language/en.json` (or whatever language you want). You need to change the `loading` property.

Getting a proper event for the loaded event of the editor turns out to be a minor nightmare. The only solution I've found works like this:

1. You add a custom script to H5PEditor as described in [the docs](https://docs.lumi.education/advanced-usage/customization). Note that adding scripts to the editor with the configuration file is currently broken, only the constructor option works. I've added a fix and it will be released soon.

The script looks like this:
```js
const finder = () => {
    if (!document.getElementById('hub-search-bar')) {
        setTimeout(finder, 20);
    } else {
        if (H5P.isFramed) {
            window.parent.H5P.externalDispatcher.trigger(
                new H5P.Event('editorinitialized', window, {
                    external: false,
                    bubbles: false
                })
            );
        }
    }
};
finder();
```
It polls until the search bar has been loaded and then checks if it runs inside an iframe. If so, it sends an event to the parent's dispatcher. 

2. In the parent, you can add something like `window.H5P.externalDispatcher.on("editorinitialized", (event) => {console.log(event)});` to subscribe to the event. You then need to figure out which component was responsible for sending the message (the window is in the event, so you can use it to identify the component) and do whatever you want with it.

While it might be possible to add this to the core, it means always injecting a custom script, which I'm not too keen on. Maybe you can extend the regular H5PEditorUI web component and add the event listener to it?

**Comment by 0xMurage** [comment]
Thank you very much. I figured injecting a custom into the editor constructor would do the trick. Since I am using the web-components package, I can poll on the frontend without injecting any script.
But the hacks aren't very reliable. I will check how the core scripts handle the initial rendering and if the logic is extensible.

**Comment by sr258** [comment]
We'd welcome a pull request if you find a clean way of doing it with the core scripts. I couldn't find any way that's better than the one I described above. One of the problems is that polling from your main page won't work as the editor is rendered by H5P in an iframe.

**Comment by 0xMurage** [comment]
Make a lot of sense. I will do more research on that and I will create a pull request if I find a clean way.
