### ISSUE TITLE
Merging H5P integration object properties should include new properties

### ISSUE THREAD

**Issue by 0xMurage** [Lumieducation/H5P-Nodejs-library#1296]
#### Libraries ,browser, and operating system info:
- Operating System: Linux
- NodeJS Version: 14
- @lumieducation/h5p-server: 7.2.0
- @lumieducation/h5p-webcomponents: 7.2.0
- 
#### Issue description:
We are using the standalone player on our [Wikonnect platform](https://github.com/tunapanda/wikonnect) (single page application) and also @lumieducation/h5p-webcomponents package for the editor.

I have noticed when a user visits the standalone player, it sets the following H5P global integration properties. 
![Screenshot from 2021-04-13 11-43-24](https://user-images.githubusercontent.com/25152892/114523971-7be5ba80-9c4d-11eb-83b0-32506590e28a.png)

When the user later visits the H5P editor page, the merge utility function of the library https://github.com/Lumieducation/H5P-Nodejs-library/blob/b0c2c1048be32bf7e5072bd20ef2cf0457aee5d6/packages/h5p-webcomponents/src/h5p-utils.ts#L8
does not include the missing new properties as below

![Screenshot from 2021-04-13 11-45-44](https://user-images.githubusercontent.com/25152892/114524386-d67f1680-9c4d-11eb-9cca-c696cbf1b061.png)

The above merged `H5PIntegration` object not include `hubIsEnabled` property.
This will signal the H5P core editor library to make an Ajax `GET` request for the available local content-type libraries as per this [LOC]( https://github.com/h5p/h5p-editor-php-library/blob/c9620109cceeaf312e9d2167679ac6cf125a317c/scripts/h5peditor-editor.js#L171)

Thus, 
i) can the H5P integration [merge function]( https://github.com/Lumieducation/H5P-Nodejs-library/blob/b0c2c1048be32bf7e5072bd20ef2cf0457aee5d6/packages/h5p-webcomponents/src/h5p-utils.ts#L8) include all new properties on resultant `window.H5PIntegration` object

ii) or the `GET` `/ajax?action=libraries` endpoint fallback to retrieving all libraries information if `machineName`, + `majorVersion`+`minorVersion` parameters don't exist?

**Comment by sr258** [comment]
Thank you for reporting this.

It would be easy to simply copy over the `hubIsEnabled` property, but I guess there are more properties that must be merged into the object if the `H5PIntegration` object comes from a different system. The current implementation assumes that H5P is only used with our implementation and that's why the merge is only partial.

My idea would be to use a deep merge library to simply merge the complete integration objects, except for the `contents` property, in which I would replace the whole content objects, to avoid issues if you switch from player to editor for the same content id. I think it would be safe to do that... Any thoughts @mimidotsuser ?

**Comment by 0xMurage** [comment]
@sr258 using deep merge for the properties (except for the contents property) is perfect and predictable.
