### ISSUE TITLE
Ajax Content-type-cache GET function returns oldest library version in spite of existing newer version.

### ISSUE THREAD

**Issue by 0xMurage** [Lumieducation/H5P-Nodejs-library#1558]
[We](https://github.com/tunapanda/wikonnect) are currently having an issue with creating the H5P branching-scenario content type. A fresh platform setup + the latest libraries work as expected. But, the H5P editor crashes when and after we try to reuse an existing branching-scenario `.h5p` file.

We have noted the files we intend to reuse contains the `H5P.BranchingScenario-1.2` library (the latest version from the hub is `H5P.BranchingScenario-1.5`). The 1.2 version does not include a `behavior` section on the `semantics.json` definition that causes the H5P editor to crash. An update of `h5p-editor-branching-scenario` was released about three weeks ago. The new release requires a `behavior` semantics definition on ` H5P.BranchingScenario-x.x` where this applies only to  `H5P.BranchingScenario-1.5`.  

**1) Issue 1:**
I could have expected the request for H5P content types to return the latest version of libraries but that's not happening.
The content-type-cache Ajax request is handled by:
https://github.com/Lumieducation/H5P-Nodejs-library/blob/c0fc609dafbc724c787388b17e20388b9d34ce99/packages/h5p-server/src/H5PAjaxEndpoint.ts#L90-L96

Drilling down from above led me to:

https://github.com/Lumieducation/H5P-Nodejs-library/blob/c0fc609dafbc724c787388b17e20388b9d34ce99/packages/h5p-server/src/ContentTypeInformationRepository.ts#L243-L248

since the local libraries on the `localLibsWrapped` property are already sorted from latest to oldest, the last index at each machineName category will always return the oldest content-type lib. I think the library should just return the first array element.

**2) Issue 2:** 
 @lumieducation/h5p-server implementation libraries naming convention is `H5P.machineName.majorVersion.minorversion` thus the above update affects all old branching scenario content.
Is it justifiable to alter the implementation to include pathVersion on the libraries name format (except on export/download)?

**Comment by sr258** [comment]
Thank you for your report! Issue 1 clearly looks like a bug. I'll have a look at this. 

Can you give a step-by-step explanation how to reproduce the error including sample files? Then I can test on my dev machine whether solving issue 1 fixes this before I do a release.

About issue 2:
In H5P installing a library in which only the patch version is updated means that the whole library is replaced. The reason is that there should never be a semantic change if only the patch version changes. Libraries with different major and minor versions can coexist and should not replace each other. H5P still tries to update libraries to the newest version when an author opens an old version editor and saves it. I don't think there's any way to avoid this.

**Comment by 0xMurage** [comment]
Steps to reproduce issue 1:


1.  Clone & set up a new demo for the project as described  https://github.com/Lumieducation/H5P-Nodejs-library#trying-out-the-demo
2.  Visit your browser and visit http://localhost:8080 
3. Click `Create new content` to load the editor
4. Get/install `Interactive Video` content type library. (_Installing branching scenario content type first misses some dependent libraries for some reason_)
5. Get/install `branching scenario` content type library
6. On successful install, test creating branching scenario content.
 Also, inspect the Ajax Get main library  requests v1.5. i.e `/h5p/ajax?action=libraries&machineName=H5P.BranchingScenario&majorVersion=1&minorVersion=5`

7. Download sample H5P branching content created by Wikonnect Team that utilizes `H5P.BranchingScenario-1.2` [here](https://we.tl/t-Cl83JfQ9XI) https://we.tl/t-Cl83JfQ9XI
8. Using the same editor configuration (latest libraries), import the downloaded h5p file above.
9. Above will crash the editor (_caused by issue 2_). Reloading/refreshing the page should reset the editor accordingly.
10. Try creating new branching scenario content type again. This was also crash the editor because it requests old version of the content type i.e. /h5p/ajax?action=libraries&machineName=H5P.BranchingScenario&majorVersion=**1**&minorVersion=**2** on this case.

**Comment by sr258** [comment]
I can reproduce the issue now. Thanks a lot for your detailed report. I'm still a bit baffled... maybe I don't fully understand what's going on. Even if I fix the first issue, I get the error.

When I try to do nr. 10 in your list, the editor crashes. I don't understand **why** it requests version 1.2 of BranchingScenario. It should request 1.5 as the content type cache references 1.5. Where does the reference to version 1.2 even come from? Do you have any idea here?

The fact that there's a new patch version of H5PEditor.BranchingScenario that references a new minor version of H5P.BranchingScenario looks like an oversight of Joubel to me. This will indeed break things at the moment, as using the old version (1.2) can't possibly work. Still, it's necessary to replace old version when there's a new patch version. I wonder whether this is caused by some malfunction of how content is updated when you open it in the editor and there's a newer version. I'll have to check this thoroughly.

**Comment by sr258** [comment]
Alright, I found the cause of this. The reason is that LibraryManager.listInstalledLibraries uses InstalledLibrary.compare and not InstalledLibrary.compareVersions. The compare method also takes into consideration the title of the library. This title was changed between 1.2 and 1.5 (the beta tag was removed) and the title took precedence over the version numbers. I've fixed this and now uploading 1.2 versions and creating new 1.5 versions works fine.

Once the CI pipelines have run through, you can test the new version.

**Comment by 0xMurage** [comment]
oooh I see, 
thank you @sr258 for your prompt assistance & the fix.
