### ISSUE TITLE
Translation files for hub and libraryMetadata JSON files start with dot

### ISSUE THREAD

**Issue by jankapunkt** [Lumieducation/H5P-Nodejs-library#1577]
I can't import some translation files from the build path: 

```js
import hubEn from '@lumieducation/h5p-server/build/assets/translations/hub/en.json';
import libraryMetadataEn from '@lumieducation/h5p-server/build/assets/translations/library-metadata/en.json';
```

However, I searched the directory and English is (as only file in these dirs) starting with a dot:

```js
import hubEn from '@lumieducation/h5p-server/build/assets/translations/hub/.en.json';
import libraryMetadataEn from '@lumieducation/h5p-server/build/assets/translations/library-metadata/.en.json';
```

All other files do not start with a dot. Is this by purpose? It was very confusing for me as I first did not find the file.

Version: `"@lumieducation/h5p-server": "^8.1.1",`

**Comment by sr258** [comment]
Yes, this is on purpose because these files are not meant to be used by the localization system. The .en files are auto-generated from the H5P Hub data and from data from library.json files. As these are already in English by default, we don't need the .en files (it would mean that updates to the English source strings on the Hub or in library.json would not be displayed). The library simply leaves the original strings in place if the language is set to English. The .en files are only there for auto-translations and so that Weblate has a source string.

**Comment by jankapunkt** [comment]
Thank you @sr258 I will therefore
 close this issue
