### ISSUE TITLE
install-library-lock-max-time-exceeded

### ISSUE THREAD

**Issue by emmanuelpineda** [Lumieducation/h5p-nodejs-library#2493]
Trying to upload existing content (h5p) sometimes returns the error "install-library-lock-max-time-exceeded", could you please help me identify the cause of the error?

![image](https://user-images.githubusercontent.com/45979790/186742175-ad1f7776-2be1-4a36-bec4-ffe75936b6e2.png)

After several attempts, the file uploads correctly:
![image](https://user-images.githubusercontent.com/45979790/186742772-b8a73d43-67b8-41b8-9cd8-063dc43936dd.png)

Thank you.

**Comment by sr258** [comment]
Hi! @emmanuelpineda This happens if a library takes too long to install and the concurrency locks run into a timeout. You can increase the timeout interval by setting `installLibraryLockTimeout` in the configuration to a higher value (https://github.com/Lumieducation/H5P-Nodejs-library/blob/013b25faba091149b20ae214e24815e5a0ff3e15/packages/h5p-server/src/types.ts#L1809)

**Comment by emmanuelpineda** [comment]
Awesome, thank you!
