### ISSUE TITLE
Getting a 404 when fetching library.json from H5P.Timeline

### ISSUE THREAD

**Issue by xenokratos** [Lumieducation/h5p-nodejs-library#2973]
Using `H5P.Timeline` i get a 404 status code on the file `library.json`

![Screenshot 2023-06-07 at 16 29 49](https://github.com/Lumieducation/H5P-Nodejs-library/assets/46603154/3a8dbc62-1637-4611-8665-870d5cb83670)

This file is supposed to be retrieved from the database ⬇️ 

https://github.com/Lumieducation/H5P-Nodejs-library/blob/dad56991512476c457c0e0343e338f222a415ebc/packages/h5p-mongos3/src/MongoS3LibraryStorage.ts#L464-L471

But it doesn’t seem to work.

I fixed it locally by removing the code above and adding the file [library.json](https://github.com/h5p/h5p-timeline/blob/master/library.json) in the S3 bucket containing the `H5P.Timeline` library.

I'm using the latest version of `@lumieducation/h5p-mongos3` and `@lumieducation/h5p-server` v9.2.1.

**Comment by sr258** [comment]
From where is library.json loaded? Normally, the library metadata is only used on the server and doesn't have to be served to the client. That's why the library only stores the library.json data in database. Still seems like a bug, though. Does this happen for every library?

**Comment by sr258** [comment]
@xenokratos Looks like I've found the issue. When you do a GET request for a library file, the server needs to know about the file's size. That's why it performs a call to `ILibraryStorage.getFileStats` in parallel to `ILibraryStorage.getFileStream`. While the later works because of the exception for `library.json` you've quoted, `getFileStats` doesn't have this exception at the moment. This should be fixed in #2984 . I'm still interested in why the library gets it's own metadata, though.

**Comment by xenokratos** [comment]
Hi @sr258 thanks for your quick reply!

It’s resolved now with the latest release (9.2.2)

Not sure why i did get that behaviour, it only happened with `H5P.Timeline` so far.
