### ISSUE TITLE
library_loader does not satisfy all needs

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#40]
Hey,

today  I wanted to use the H5P-Nodejs-library to load and resolve dependencies within the H5P-Editor-Nodejs-library. The Editor needs to load all .json files (library.json, semantics.json, translation.json) from library-folders, while the renderer only loads the library.json. So we would have to provide the Editor with a library_loader, a semantics_loader, and a translations_loader, which is a little bit much for the API.

If we stick to the old way (providing only the library_directory as a path and requiring the .json files) we have a much simpler, but more restricted API.

What are your thoughts about this issue? @rtens

**Comment by rtens** [comment]
I'd rather not have that dependency on the file system. For one because it makes testing harder, and also because these objects might not be stored in the file system but in a database (e.g. on Heroku where you don't have a persistent file system).

How about passing an `LibraryFileLoader` instance that can `loadLibrary()`, `loadSemantics()` and `loadTranslation()`?

**Comment by JPSchellenberg** [comment]
I think this issue is related to Lumieducation/H5P-Editor-Nodejs-library#10. We need to provide an interface that has to be implemented by the user.
One for the Renderer and one for the Editor, because the Renderer only needs a `loadLibrary()` function. The Editor requires a more complex `DataLoader()`.

**Comment by rtens** [comment]
I agree. But I would call it something more specific than `IH5PInterface`.

**Comment by JPSchellenberg** [comment]
As we divided the interface into different functions (see Lumieducation/H5P-Editor-Nodejs-library#10) I will close this issue.
