### ISSUE TITLE
Merge h5p-editor-nodejs-library and h5p-nodejs-library

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#55]
The more I look at h5p-editor-php-library and h5p-php-library, the less does the distinction between the two make actual sense to me: Many things that are clearly part of the editor (content and package validation, file upload, ...) are part of h5p-php-library. As far as I know the "player" can't be used without also having the editor in current PHP implementations. There are also many dependencies of the editor on the other library, which makes the whole h5p project difficult to understand for new programmers, because you constantly have to switch between projects and lose things like "Go to definition" in IDEs. 

So why have to separate projects at all? If there should be a standalone "player" application, you could always start the application with a special flag or change something in the configuration to disable the editor.

**Comment by JPSchellenberg** [comment]
You might be right. My first approach was to put everything in one repository, but I decided to try to be as close as possible to the PHP-implementation. But the more I learn about it the more I think we should move away from the PHP-implementation as it suffers heavily from technical debt.

**Comment by rtens** [comment]
As far as I remember, the original idea was to have a very simple library for the Player to ease integration. The assumption is that there would be applications that don't need an Editor and only want to play H5P Packages. Editing could be done with a desktop application.

I don't see why the Player needs content and package validation or file upload. The Player just plays the Package content.

So yes, if there are dependencies between the two projects, we should put them into a single repository. But I'd rather try to avoid dependencies and keep the simple and small Player project. We definitely should not try to copy the design of the PHP implementation.

So @sr258, are there any cases where you need switch between the two nodejs projects? If so, what are they?

----------

I would also like to suggest a way of handling this kind of discussion. I think the Assignee of an issue should be the (preferably single) person responsible for making sure the issue is eventually closed. To involve other people into the discussion, I would suggest to mention them in a comment.
This way, responsibilities would be more clear and participation would be an opt-in.

**Comment by sr258** [comment]
If the player is only responsible for viewing content it might be fine to have it there. I'm fine with the separation if our implementation doesn't follow the structure of the PHP implementation.

Areas in which there will have to be common code might be:
* Handling of sessions
* Dealing with users & access permissions
* Generating exports
* content, library and user state repositories (probably the biggest annoyance)

**Comment by rtens** [comment]
OK so we keep it as it is right now and try to keep the Player as lightweight as possible. If there turns out to be significant overlap we merge the repos.

I consider this issue resolved. Please re-open if it's not.

**Comment by JPSchellenberg** [comment]
Hey, 
As @sr258 mentioned the export function needs code from the editor. I would like to merge the player into the Editor-repository as I think it makes the development process easier and more sustainable. If someone only wants to use the player, he just needs to import the player with `import { H5PPlayer } from 'h5p-nodejs'` or something like that. 

@sr258  What do you think about merging?

**Comment by sr258** [comment]
Yes, I think a merge simplifies development and we should do it. But we should really remember to couple player and editor as loosely as possible. The best way will be to only use interfaces instead of concrete classes whenever possible.

**Comment by JPSchellenberg** [comment]
Alright. I think this would be the next step.

**Comment by JPSchellenberg** [comment]
Just to let you know: I am starting to work on this one.
