### ISSUE TITLE
Use temporary folder for uploaded content files

### ISSUE THREAD

**Issue by rtens** [Lumieducation/H5P-Nodejs-library#61]
This issue combines #23 and #33.

Currently, when uploading files during editing (eg by adding a picture to a Course Presentation slide), the file is stored in the content folder (under `h5p/content/{contentId}/content/{fileName}`).

This leads to the problem that if the changes are not saved and the file is not used in the end, it will still be part of the package and not be deleted.

A possible solution would be to store uploaded files in a temporary folder and only move them to the content folder when the changes are saved.

The temporary folders should be regularly purged.

**Comment by sr258** [comment]
I've given this some thought and I think it would be better to have preliminary content in the storage instead of having a global temporary storage location from which the files are copied when the corresponding piece of content is finally saved. Every time a user opens the editor, a preliminary content entry is created with a timeout after which it is deleted automatically if it hasn't been saved permanently until then.

- this reduces complexity in the editor module (no need to differentiate btw. creating new content and editing existing content; no need for a special temporary files module that has to keep track of unsaved sessions, manage associations btw. content files, users and sessions etc.)
- this makes saving preliminary content states easier in the future (e.g. regularly saving the state of content.json to recover from crashes/connection drops)

@rtens @JPSchellenberg What do you think of this approach?

**Comment by rtens** [comment]
Not sure if this works (at the the way I understood it) since it's only the content files that are uploaded, the content.json itself is not updated with each file upload. So the preliminary content would be have the new files but the old content.json.

**Comment by sr258** [comment]
I thought of having a database entry without content.json. This should be not problem and you simply add the content.json contents later.

**Comment by rtens** [comment]
My gut feeling leans towards keeping the temporary files separate and copying them over on save. But only slightly.
