### ISSUE TITLE
Optional callback

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#65]
Hey,

I think we should provide the option to use callbacks instead of promises.
I would do it the standard nodejs-way. The last argument of the constructor is the callback and it is optional. If you want to use the callback you provide the callback as the last argument. If you want to use promises you omit the callback and the constructor returns a promise.

**Comment by rtens** [comment]
After reconsideration I disagree with your conclusion. I think the reason many node libraries use this convention is because they added promises later and wanted to stay backwards compatible.

Supporting both complicates the function interface and implementation. I vote to use promises only.

What do you thing, @jpschellenberg?

**Comment by rtens** [comment]
@JPSchellenberg Any update regarding the minimum node version we need to support?

**Comment by rtens** [comment]
Since we agreed to only use Promises, we can close this issue.
