### ISSUE TITLE
Asynchronous library loader

### ISSUE THREAD

**Issue by rtens** [Lumieducation/H5P-Nodejs-library#68]
@JPSchellenberg @danielrudn

I realized I need some clarification and hope you can help me: Why do we need an async library loader? I suspect it got something to do with the editor but I couldn't find the exact reason.

And if the loader needs to be async then I would say we drop the sync option altogether. Any objections from your sides?

**Comment by danielrudn** [comment]
To give an example, I needed the async library loader since my app has all h5p related files uploaded to S3. The library loader I implemented would fetch the `library.json` from S3 and that needs to be async.

I think we should keep the sync loader option since it is still useful to just `require(somelib-1.5.json` without returning a promise from the libraryLoader function.

Also removing the sync option would cause breaking changes since any sync libraryLoader would need to be changed to be async.

**Comment by rtens** [comment]
Ah yeah that's a good reason. 

Still, I will remove the sync option. It's unnecessary duplication since you can always turn wrap a sync call into a Promise. The project is still in an experimental stage so backwards compatibility shouldn't be a concern.

**Comment by JPSchellenberg** [comment]
The sync-libraryLoader was an interim solution because I couldn't make the async-libraryLoader work properly. But thanks to @danielrudn with the new PR (#66) we can remove the sync-libraryLoader. I agree with @rtens: see no reason to keep it, as we are still in an experimental stage
