### ISSUE TITLE
Moving license to AGPL?

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#85]
Considering the fact that we're building a server application, it [would make sense to use the AGPL license ](https://www.gnu.org/licenses/why-affero-gpl.de.html) instead of GPL. That way someone who uses the project to run a server and changes the code has to publish it too. Under the GPL this would not be necessary.

**Comment by JPSchellenberg** [comment]
When I put the GPL license on it, I just followed what H5P was doing. I would agree with you and have no problem when we switch to AGPL.

**Comment by JPSchellenberg** [comment]
@rtens what do you think?

**Comment by dailez** [comment]
I think GPL and AGPL are not good for the widespread adoption of the library. The H5P content types are all MIT licensed. The h5p-editor-php-library (editor) is also covered by this license. H5P tries to use the MIT license wherever possible due to the freedom it gives (see https://h5p.org/licensing). The only exception at the moment is h5p-php-library (core) which uses some third party code for purifying the user input. But the GPL-part of the code will be made optional soon in order to make it possible to use H5P in software that isn't GPL compatible. General, in the context of Node.js and Javascript GPL libraries are rather the minority (MIT dominates) and do not enjoy great popularity. So, if you want the library to be used on a large scale, then go for MIT rather than (A)GPL.

**Comment by jankapunkt** [comment]
@dailez this is a fork with modifications from a GPL repository and the GPL is very clear about the copyleft. There is no way to change it ti MIT unless the original will be MIT.

-----
Edit: I am not sure, whether this is 100% true, as is not a direct fork. The question is, if it is considered a "derivative work" which implies a modification of the original. This remains to be discussed.
-----

There is also no issue with GPL that prevents you from using it in  a commercial product, because as long as you not modify the core code you are not to forced to publish the code (because it is in that state published anyway). The sheer including of the code into your software service or running it as a service does not imply any negative effect on your business.

There are thousands of companies worldwide making money, just by hosting and configuring wordpress, moodle, drupal etc. and these are GPL, too.

MIT is more free but also causes too many mutations of the same framework while GPL tends to draw in more commits to the core repository.

The AGPL is only an extension of GPL where the same principle of the GPL applies for service providers, so summarized

* with GPL, runnin a service, that includes a modified version of this repo would not need to be published, while a distribution of a modification would need to be published
* with AGPL also a running online service, using this repo in a modified state would require it to be published

so here you should be careful, because the AGPL would also imply for someone who applies a "fix" or a customization of the code to make it run on their infrastructure to require them to publish the code.

>  General, in the context of Node.js and Javascript GPL libraries are rather the minority 

And this is great but the original is a GPL, so the copyleft applies and has to be respected.

**Comment by sr258** [comment]
I don't agree that its a fork or a derivative work. The only parts that are directly copied from some other place are in ```src/client``` and could be easily replaced. All other code is completely new, but obviously follows the same interface structure. As interfaces don't have a copyright (at least not in Germany, where all current authors reside), I don't see how this work is a derivate. 

I still agree, that its fine to leave the license as GPL, but I don't see why it should be a problem with the AGPL license to publish small fixes or customization by creating a fork here on GitHub. This is done in many other projects, too, and would make sure that bigger changes are also published and can be used upstream. We're building an online service after all, and the AGPL is exactly for this.
